const projectsData = [
    {
      title: "Weather App Frontend",
      description: "Frontend for a weather application.",
      techStack: "React, JavaScript",
      keyFeatures: ["Real-time weather updates", "Responsive design"],
      challenges: "Integrating with a weather API.",
      demoLink: "https://github.com/username/weather-app-frontend",
    },
    {
      title: "Weather App Backend",
      description: "Backend for a weather application.",
      techStack: "Node.js, Express.js, MongoDB",
      keyFeatures: ["API integration", "Database management"],
      challenges: "Handling real-time data.",
      demoLink: "https://github.com/username/weather-app-backend",
    },
    {
      title: "Restaurant Reservation App (Admin)",
      description: "Admin dashboard for restaurant owners to manage their restaurant details and reservations.",
      techStack: "React Native, MongoDB, Node.js",
      keyFeatures: ["Admin dashboard", "Reservation management"],
      challenges: "Handling real-time updates.",
      demoLink: "https://github.com/username/Restaurant-Reservation-App-Frontend-Admin",
    },
    {
      title: "Restaurant Reservation App (User)",
      description: "User platform for users to make reservations to various restaurants.",
      techStack: "React Native, MongoDB, Node.js",
      keyFeatures: ["User dashboard", "Reservation system"],
      challenges: "User authentication and authorization.",
      demoLink: "https://github.com/username/Restaurant-Reservation-App-Frontend-User",
    },
    {
      title: "Shopping List Mobile App",
      description: "Mobile app for managing shopping lists.",
      techStack: "React Native, JavaScript",
      keyFeatures: ["Add, Edit, Delete Items", "Offline support"],
      challenges: "Handling offline data synchronization.",
      demoLink: "https://github.com/username/shopping-list-mobile",
    },
    {
      title: "Image Gallery",
      description: "A web application for displaying images in a gallery format.",
      techStack: "React, JavaScript",
      keyFeatures: ["Image upload", "Responsive gallery"],
      challenges: "Optimizing image loading.",
      demoLink: "https://github.com/username/image-gallery",
    },
    {
      title: "Employee Registration App",
      description: "An app for managing employee registrations.",
      techStack: "React, Node.js, MongoDB",
      keyFeatures: ["Employee registration", "Database management"],
      challenges: "Handling form validation.",
      demoLink: "https://github.com/username/Employee-Registration-App",
    },
    {
      title: "Recipe App",
      description: "A mobile app for managing recipes.",
      techStack: "React Native, JavaScript",
      keyFeatures: ["Recipe management", "Search functionality"],
      challenges: "Integrating with a recipe API.",
      demoLink: "https://github.com/username/mobile-recipe-app",
    },
    {
      title: "Audio Recorder",
      description: "A mobile app for recording audio.",
      techStack: "React Native, JavaScript",
      keyFeatures: ["Audio recording", "Playback functionality"],
      challenges: "Handling audio file storage.",
      demoLink: "https://github.com/username/Audio-Recorder",
    },
    {
      title: "Library Management System",
      description: "A system for managing library books and members.",
      techStack: "Node.js, MongoDB",
      keyFeatures: ["Book management", "Member management"],
      challenges: "Handling database relationships.",
      demoLink: "https://github.com/username/Library-Management-System",
    },
    {
      title: "Quiz Application",
      description: "A web application for creating and taking quizzes.",
      techStack: "React, Node.js, MongoDB",
      keyFeatures: ["Quiz creation", "Score tracking"],
      challenges: "Handling real-time updates.",
      demoLink: "https://github.com/username/quiz-application",
    },
    {
      title: "Hotel App",
      description: "A web application for managing hotel bookings.",
      techStack: "React, Node.js, MongoDB",
      keyFeatures: ["Booking management", "Room availability"],
      challenges: "Handling real-time updates.",
      demoLink: "https://github.com/username/hotel-app",
    },
    {
      title: "Redux Shopping List",
      description: "A shopping list app built with Redux.",
      techStack: "React, Redux, JavaScript",
      keyFeatures: ["Add, Edit, Delete Items", "State management with Redux"],
      challenges: "Managing state with Redux.",
      demoLink: "https://github.com/username/redux-shopping-list",
    },
    {
      title: "To-Do List",
      description: "A simple to-do list app.",
      techStack: "React, JavaScript",
      keyFeatures: ["Add, Edit, Delete Tasks", "Task filtering"],
      challenges: "Handling asynchronous data updates.",
      demoLink: "https://github.com/username/to-do-list",
    },
    {
      title: "UI Challenge",
      description: "A challenge to replicate a UI design.",
      techStack: "HTML, CSS, JavaScript",
      keyFeatures: ["Responsive design", "UI replication"],
      challenges: "Matching the design exactly.",
      demoLink: "https://github.com/username/ui-challenge",
    },
  ];
  
  export default projectsData;